POST http://localhost:8080/odata/v4/CatalogService/postItems
Content-Type: application/json
Authorization: Basic authenticated:

{
    "items": [
        {
            "bookNo": 10,
            "title": "Postman1",
            "stock": 1
        },
        {
            "bookNo": 11,
            "title": "Postman2",
            "stock": 1
        }
    ]
}