---
spring:
  config.activate.on-profile: cloud
  web.resources.static-locations: file:./app/
  datasource:
    url: 'jdbc:sqlite:sqlite.db'
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql.init.mode: embedded
logging:
  file.name: ./application.log
  level:
    com: info
    org: info
cds:
  security.mock.users:
    - name: admin
      password: admin
      roles:
        - admin
      attributes:
        businessPartner:
          - "10401010"
    - name: user
      password: user
